### ISSUE TITLE
Question: is there documentation of the reasoning for the cff names fields?

### ISSUE THREAD

**Issue by datakid** [citation-file-format/citation-file-format#111]
I was wondering about the decision to have a `family-names` and `given-names` instead of a single `name` field in the cff format?

While it is tongue in cheek, I think that that the article [Falsehoods programmers believe about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) contains some truth. 

But my argument for a single name field would essentially be: you are putting searching a database easily above and before the mental effort that everyone who doesn't have a first-name last-name will need to exert. Searching databases is a much easier problem to solve because it's within the developer's control.

**Comment by sdruskat** [comment]
Hi @datakid, thanks for this question!

There is some documentation here: https://github.com/citation-file-format/citation-file-format#person-objects. 

Also, `name` also exists and you can use it for people instead of course. The use case for having this name split was based on compatibility with other formats and not so much about search.

**Comment by datakid** [comment]
Wow, absolutely my bad for not reading further - I had no idea the README was so long. Apols - thanks for the cff!

**Comment by sdruskat** [comment]
No worries! It *is* a long `README`. Perhaps we can find a more digestible form of presenting the format at some point without losing the details along the way...
