### ISSUE TITLE
Support for datasets?

### ISSUE THREAD

**Issue by arfon** [citation-file-format/citation-file-format#113]
:wave: hello! It's a delight to see CFF in such good shape - I love the thought and care that has gone into this project.

I wondered if you'd given any thought to supporting datasets/data records in CFF, i.e. extending what you already have here for software? I'm imagining there would have to be some kind of top-level `type` field (e.g., `type: software`, `type: dataset`) to differentiate the two, and quite possibly some additional work on the wider data model to support the recommendations of the [data citation principles](https://www.force11.org/datacitationprinciples).

Please forgive me if this has already been discussed, I couldn't find anything in the issues on this repo.

/ cc @npch as we were chatting about this the other day.

**Comment by sdruskat** [comment]
Hi @arfon, great to hear from you and thanks both for this suggestion and for your patience.

> It's a delight to see CFF in such good shape - I love the thought and care that has gone into this project.

Thanks!
 
> I wondered if you'd given any thought to supporting datasets/data records in CFF, i.e. extending what you already have here for software? I'm imagining there would have to be some kind of top-level `type` field (e.g., `type: software`, `type: dataset`) to differentiate the two, and quite possibly some additional work on the wider data model to support the recommendations of the [data citation principles](https://www.force11.org/datacitationprinciples).
> 
> Please forgive me if this has already been discussed, I couldn't find anything in the issues on this repo.

Interesting proposition, and no, this hasn't been discussed anywhere yet :slightly_smiling_face:.

I imagine a format such as CFF could be just as useful for maintainers of datasets as it can be for developers/maintainers of software. As for including datasets in the scope of CFF, I think we'd need to discuss the pros and cons of such a multi-purpose format.

We (me, @jspaaks, @LourensVeen) have recently started putting some thought into the purpose, scope and structure of CFF to consolidate it a bit more, and create a solid base for other solutions to build on. In the course of this, we have also decided to strictly focus on the *citation* scenario (as of now for software only), and avoid "scope creep", because we think that this would eventually lead to something that CodeMeta is already trying to do.

I do think that widening the scope to include datasets would be going in a different direction (say *vertical*) than what we're trying to avoid (say *horizontal* scope creep), but I can't say yet whether I think it'd be a good idea. This is because I'd like to avoid making something that we hope is simple enough for people to start using it with as little extra effort as possible, into something that is even a tiny wee bit too complex and puts people off.

Perhaps we could do two things to determine feasibility:

1. Collect pros and cons of having one citation file format for both software and data.
2. Come up with a diff of sorts that would show what we'd need to add to CFF in order for it to support datasets.

What do you think?

**/cc @jspaaks**

**Comment by arfon** [comment]
> We (me, @jspaaks, @LourensVeen) have recently started putting some thought into the purpose, scope and structure of CFF to consolidate it a bit more, and create a solid base for other solutions to build on. In the course of this, we have also decided to strictly focus on the citation scenario (as of now for software only), and avoid "scope creep", because we think that this would eventually lead to something that CodeMeta is already trying to do.

Makes sense. 💯 to the focus on citation.

> Perhaps we could do two things to determine feasibility:

> 1. Collect pros and cons of having one citation file format for both software and data.
> 2. Come up with a diff of sorts that would show what we'd need to add to CFF in order for it to support datasets.

These sound like great next steps. I'd be more than happy to contribute to this discussion however you'd like to have it.

**Comment by sdruskat** [comment]
Just to confirm that version [1.2.0](https://github.com/citation-file-format/citation-file-format/pull/120) will include a new optional key `type` with enum values `['dataset', 'software']` :slightly_smiling_face:: https://github.com/citation-file-format/citation-file-format/pull/120/commits/a6170278856703bb11d44ced14be5dfc7e3f41d0.

**Comment by sdruskat** [comment]
Think we should still do a sanity check for licenses (should at least include the most common ones for data?).

**Comment by jspaaks** [comment]
> Think we should still do a sanity check for licenses (should at least include the most common ones for data?).

I think that warrants its own issue to avoid scope creep here

**Comment by sdruskat** [comment]
> > Think we should still do a sanity check for licenses (should at least include the most common ones for data?).
> 
> I think that warrants its own issue to avoid scope creep here

This is #180.

**Comment by sdruskat** [comment]
Closing, this will come in `1.2.0`.
