### ISSUE TITLE
Add identifier "arxiv"?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [citation-file-format/citation-file-format#254]
Following the suggestion [here](https://github.com/citation-file-format/citation-file-format#identifier-type-strings) I'm opening this issue, since I would like to refer to an `arxiv` preprint via the identifier object. Ideally, by just providing the ID (see https://arxiv.org/help/arxiv_identifier). Currently I would either use `other` or `url`.

I am not sure whether this is the actual use-case of identifier objects, since arXiv preprints don't point to a specific version of a repository or source code but they are pointing to a publication. However, since I did not find a lot of information with respect to arXiv in [existing issues](https://github.com/citation-file-format/citation-file-format/issues?q=arXiv) I thought it might be a good idea to start this discussion here.

Related: According to https://github.com/citation-file-format/citation-file-format/issues/102#issuecomment-565093412 arXiv seems to be used in zenodo.

**Comment by sdruskat** [comment]
Hi @BenjaminRodenberg and thanks for opening this issue.

Can I ask whether you want to reference the ArXiv preprint from within a `reference` object (i.e., is the preprint a reference of the software you describe, or meant to represent the software itself?), or in the "root" document? The latter is reserved for actual software metadata, so an `arxiv` identifier wouldn't make much sense here. 

If you want to add this to a reference though, I think this could be a reasonable case for adding such an identifier. For the time being, I'd suggest to use the catch-all `other` identifier type, e.g.:

```yaml
references:
  - title: "ArXiv preprint"
    ...
    identifiers:
      - type: "other"
        value: "arXiv:1905.08674"
```

Would this work?

**Comment by BenjaminRodenberg** [comment]
My use-case is very similar to what @emstoudenmire describes and I also observed this problem with the exported bibtex file. Here are the two alternatives I'm currently considering:

1. [Put arXiv paper into `references`](https://github.com/precice/fenics-adapter/blob/b8c0d11a62920218ba26ba9b8b31fa529f806bab/CITATION.cff#L39-L71) (Intended use)
2. [Use arXiv paper as root](https://github.com/precice/fenics-adapter/blob/99f2d98a47c2dbd6a1d785f79fc965abf97bae05/CITATION.cff#L1-L47) (As far as I understand not the intended use)

From @sdruskat's [comment above](https://github.com/citation-file-format/citation-file-format/issues/254#issuecomment-888350540) *The latter is reserved for actual software metadata, so an arxiv identifier wouldn't make much sense here.*  I understand that case 1. is intended use and 2. is not intended use.

For case 1. the "cite this repository" button only gives me a bibtex file containing the reference to the code, not to the paper. So the paper remains invisible. For case 2. the "cite this repository" button refers to the paper. But this might already be a different issue (?).

For now the solution proposed in https://github.com/citation-file-format/citation-file-format/issues/254#issuecomment-888350540 is a good work around. I already implemented it in https://github.com/precice/fenics-adapter/commit/ec92e731855337151e50037d7e4caafe7a804d16.  From my perspective ideally the following format could be used in the future:

```
references:
  - title: "ArXiv preprint"
    ...
    identifiers:
      - type: "arxiv"
        value: "1905.08674"
```

**Comment by sdruskat** [comment]
Thanks @emstoudenmire and @BenjaminRodenberg.

As this is a common use case - wanting users to cite a paper - the next version of CFF (1.2.0, coming soon) will include a new field `preferred-citation` which is meant exactly for this purpose. It allows you to add a (one) reference that you ask users to cite instead of what's in the root of the CFF file (i.e., the software itself). So I hope that this is good news :slightly_smiling_face:.

One note though, software in itself is a valuable and important research output (as you will know), and the [Software Citation Principles](https://peerj.com/articles/cs-86/) argue that the software as the actual output should always be cited, even if you ask people to also cite a paper. This is something that you could mention in the `message` field of your CFF file. Citing the software itself also supports reproducibility, especially if newer versions of the software are used, and there is no dedicated paper for the version, and a paper may already be outdated.

**Comment by emstoudenmire** [comment]
Thank you Stephan, that does sound like the feature we need. I appreciate the feedback about citing the software: in fact the journal we are publishing our paper in is a new one which has this goal in mind. The plan for that journal is to associate two DOIs to the work, one for the paper (so that it can be tied to various citation tracking systems, be received by the academic field, etc.) and the other for a major release of the software itself. (The journal is called "SciPost Physics Codebases" and if it takes off, I think there is a plan to expand to other areas of scientific software besides physics.)

**Comment by sdruskat** [comment]
Closing this, as ArXiv identifiers cannot identify software, and the `preferred-citation` field solves asking people to cite a paper instead (better: in addition to) the software.
