### ISSUE TITLE
Software version required for citation parsing

### ISSUE THREAD

**Issue by PSSF23** [citation-file-format/citation-file-format#313]
Though not stated in the [format guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)'s "minimal example," I found **software version** to be necessary for successful parsing. It could potentially be a bug, or the guide needs to be updated.

**Comment by sdruskat** [comment]
Thanks for opening this issue @PSSF23!

I assume that by "citation parsing" you mean the GitHub functionality where the citation is displayed on repository landing pages?  
If so, this is not actually something that is under our control.

### A brief explanation of the components that make up the GitHub feature:

#### Schema

The Citation File Format provides a schema that is developed in this repository. As of schema version [`1.2.0`](https://github.com/citation-file-format/citation-file-format/releases/tag/1.2.0), the `version` field is [not longer required](https://github.com/citation-file-format/ruby-cff/) (but it had been up to version [`1.1.0`](https://github.com/citation-file-format/citation-file-format/releases/tag/1.1.0)). The [schema guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md) represents the latest version (`1.2.0`). (The specs for `1.1.0` can be found [here](https://github.com/citation-file-format/citation-file-format/tree/1.1.0).)

#### Reading/conversion

The [`ruby-cff`](https://github.com/citation-file-format/ruby-cff/) Gem provides reading and parsing functionality for `CITATION.cff` files, and converts the information in them to the BibTeX and citation strings. AFAIK, the Gem supports CFF schema `1.2.0` in the [latest version 0.8.0](https://github.com/citation-file-format/ruby-cff/releases/tag/v0.8.0).

#### GitHub's citation feature

GitHub uses the `ruby-cff` Gem to retrieve these citation strings to display in their UI. I'm assuming that they still use an older version of the Gem which supported CFF schema `1.1.0` (the one where `version` was required), but _they will update soon_.

---

If the GitHub feature is what you are referring to, I'll move this issue to the `ruby-cff` repository so that it can be tracked there (for want of a better pace to track the GitHub feature) and will ping the developers and our person at GitHub to take note (and perhaps close once the Gem has been updated).

**Comment by PSSF23** [comment]
@sdruskat Thanks! Please move the issue as you see fit.

**Comment by PSSF23** [comment]
By the way, I used `CFF 1.1.0` because the `cffinit` [website](https://citation-file-format.github.io/cff-initializer-javascript/) only supports that version.

**Comment by sdruskat** [comment]
@PSSF23 I see. `cffinit` is undergoing a major upgrade at the moment, which will support version 1.2.0, due later this year. What do you think would help users be aware that the old `cffinit` website supports only 1.1.0?

In other news, I think that the updated Gem will be rolled out to GitHub this week, so that version 1.2.0 should be fully supported then.

**Comment by sdruskat** [comment]
Closing this. If you still find issues with rendering citation strings on GitHub, please open a new issue in the [ruby-cff](https://github.com/citation-file-format/ruby-cff/) repo.
