### ISSUE TITLE
DOI for our own `CITATION.cff` is not rendered in GitHub

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#318]
None of the `doi`s provided in `identifiers` is being used for rendering, which is probably understandable seeing that they're hard to disambiguate. Perhaps we should provide the version DOI in the root `doi` field?

https://github.com/citation-file-format/citation-file-format/blob/main/CITATION.cff#L36-L42

APA string: Druskat, S., Spaaks, J. H., Chue Hong, N., Haines, R., Baker, J., Bliven, S., Willighagen, E., Pérez-Suárez, D., & Konovalov, A. (2021). Citation File Format (Version 1.2.0) [Computer software].

Is this called *choking on your own dog food*? :laughing:

**Comment by jspaaks** [comment]
If I remember correctly, cffconvert uses a preferred order, something like search for a doi in `identifiers` first, but if you there arent any, use `doi`

**Comment by sdruskat** [comment]
Yes, but I guess this would be ruby-cff, no?

**Comment by jspaaks** [comment]
> Yes, but I guess this would be ruby-cff, no?

Indeed.

As you know I would be in favor of either deprecating or discouraging use of `doi` due to its inherent ambiguity. I much prefer `identifiers`, especially if we would be able to annotate items there with datacite-like terms for better machine readability.

While we sort this out, we could take a pragmatic approach and duplicate the information from `identifiers[1]`. Nonetheless I think it would be good to ask @hainesr to also support dois from identifiers, since the [new version](https://citation-file-format.github.io/cffinit/) of cffinit will use (only) that.

**Comment by hainesr** [comment]
I'm happy to support DOIs from `identifiers` in ruby-cff, but what to do if there are multiple DOIs specified?

**Comment by sdruskat** [comment]
> I'm happy to support DOIs from `identifiers` in ruby-cff, but what to do if there are multiple DOIs specified?

@hainesr We're thinking that this could be solved partly through heuristics, see, e.g., #330.
