### ISSUE TITLE
Support for multiple citations?

### ISSUE THREAD

**Issue by sroet** [citation-file-format/citation-file-format#339]
First of all, sorry if this has been asked before, but I could not find it when searching the issue-tracker.

**Issue:**
A [repository](https://github.com/openpathsampling/openpathsampling) I am currently maintaining had a **pair** of academic papers published coupled with its 1.0 release. Therefor, their [preferred citation](http://openpathsampling.org/latest/#citing) is done by citing **both**.  This does not seem to be supported (for example, having multiple `doi` fields breaks the validation)

For now I am using a citations.md, as I could not figure out how to do this within a cff schema.

Which leaves me with 2 questions:

1) Did I miss some way of doing this?
2) If not, is there any intention of supporting this edge-case? 

I can understand completely if this edge-case is not intended to be covered or supported, (I can easily imagine forcing non-duplicate keys is favored), but I could not find any documentation/issue stating explicitly that the schema is supposed to be a single citation.

cc: @dwhswenson

**Comment by sdruskat** [comment]
Hi @sroet, and thanks for opening this issue

> First of all, sorry if this has been asked before, but I could not find it when searching the issue-tracker.

No worries, this hasn't been asked yet, thanks for having a look before asking!

> **Issue:**
> A [repository](https://github.com/openpathsampling/openpathsampling) I am currently maintaining had a **pair** of academic papers published coupled with its 1.0 release. Therefor, their [preferred citation](http://openpathsampling.org/latest/#citing) is done by citing **both**. This does not seem to be supported (for example, having multiple `doi` fields breaks the validation)

Interesting example! And yes, you can only have one `doi` field, which is meant to take up the DOI for the software and is sort of a shorthand for having a more complex entry in `identifiers` (see [this section in the schema guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#doi)).

> For now I am using a citations.md, as I could not figure out how to do this within a cff schema.
> 
> Which leaves me with 2 questions:
> 
>     1. Did I miss some way of doing this?

Not really, but read on :).

CFF tries to support the [software citation principles](https://doi.org/10.7717/peerj-cs.86) as best it can. The principles state that the software itself should be cited regardless of any papers that exist around it. Therefore, allowing something like a [`preferred-citation` section](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#credit-redirection) in the CFF file that allows you to define one (1) reference to something that should be cited along with (or instead of) the software, has been done to enable people to get credit for some software-related work *now*, but with a bit of teeth grinding only. The software is the actual output, and there are issues with discoverability and reproducibility if people only cite a paper.

*However*, if you cannot decide for just one paper to go into `preferred-citation`, you can potentially hack the `identifiers` section to at least provide both DOIs. Include them both there, and provide a description that lets people know what they resolve to.

They could also go into the `references` section, but this isn't the best place, as the papers should cite the software they describe, not the other way round :wink:.

>     2. If not, is there any intention of supporting this edge-case?

I don't think we will "soften" support of best practice - as defined in the principles paper linked above - any further than we already have by providing the `preferred-citation` key. So no, no intention to support this I'm afraid. Sorry.

> I can understand completely if this edge-case is not intended to be covered or supported, (I can easily imagine forcing non-duplicate keys is favored), but I could not find any documentation/issue stating explicitly that the schema is supposed to be a single citation.

Well, the format itself is for describing "a software", although perhaps we don't actually have a good definition of what "a/one software" actually is. Should go in the *Future research* section :slightly_smiling_face:.

If this answers your question well enough, please feel free to close this issue, or continue the conversation!

**Comment by sroet** [comment]
> If this answers your question well enough, please feel free to close this issue, or continue the conversation!

Thank you so much for the in-depth answer (and the interesting principles paper)!
It answers all my questions and I will keep CFF in mind for any other suitable software(s).
