### ISSUE TITLE
Introduce key to record `article-number`?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#347]
In [this comment](https://github.com/citation-file-format/citation-file-format/issues/343#issuecomment-920161004), @jodischneider suggested that many papers today are cited via an _article number_ (or ID I guess), rather than page range (which makes sense).

Think about whether a new version of CFF should introduce a new dedicated key to take this information, or whether existing keys can be used for this.

**Comment by AdityaSavara** [comment]
I encounter this frequently in the course of my work.  My experience is that journal bibliographies and endnote work fine if we put the article-number in the "First Page" field.  From my experience, I infer that the people are supposed put this in the same field that first page would go into. Personally, I find "start" and "end" a bit confusing.  It might be useful if we have an "Index / Glossary" of features  in addition to the schema. When I go to this page and search for "First Page" I don't find anything. Thoug the "pages" field is there, and I would have (incorrectly) used the pages to specify "which" pages the reference was for, rather than the total number of pages.

https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsreferencepages

To clarify my glossary/index comment: The schema is for *forward* searching, we would benefit from a resource for *reverse* searching "what field do I put a first page in?"

**Comment by jspaaks** [comment]
We could also add a note to the definitions of `start` and `end` and `pages`, explaining how they play together.

Also we could consider adding an FAQ section in between "Credit redirection" and "Valid keys" where some recurring questions may be answered.

**Comment by AdityaSavara** [comment]
I too believe that putting this info in the notes of these definitions in the schema is good for now. 

I also considered the idea of this in FAQ, But the schema is so big that I think in the long run a (reverse) glossary/index will end up being useful. Not short-term critical.

**Comment by sdruskat** [comment]
Although it's not optimally named, we'll change the documentation for `reference.number` to make clear that this is a good key to use for article IDs.

**Comment by sdruskat** [comment]
Closing as resolved in #519.
