### ISSUE TITLE
`type` should accept an array, because single repo can contain both a dataset and software processing it

### ISSUE THREAD

**Issue by KOLANICH** [citation-file-format/citation-file-format#367]

**Comment by sdruskat** [comment]
HiI @KOLANICH, thanks for opening this issue.

I understand the motivation behind this feature, but am hesitant to implement it.

The reason for this is that it carries semantic issues, and in a way introduces a third object that CFF would then cover: a `repository` (in addition to `software` and `dataset`). CFF is lightly opinionated towards following good practice, and in this case, the best practice would be to separate code and data in some way in the repository, e.g., by putting them in different directories. Then, each directory would hold its own `CITATION.cff`, problem solved.

The downside of this is that you'd lose the GitHub widget (I think). If you'd want to use that, you'd have to separate code and data into separate repos. While I understand that this may not be what some people want, it is a much cleaner solution and follows the separation of concerns principle.

What do you think?

**Comment by KOLANICH** [comment]
Yeah, I also thought like that, though it is not always practical. Git submodules have terrible UX and having additional updating code is burden.

**Comment by sdruskat** [comment]
I understand your point. However, I think that the issues that exist with structuring a repository and keeping it updated should not influence the CFF schema in the way you suggest.

Two additional things that I hope may help:

1. Git submodules aren't needed for a decent repository structure that also works with the way CFF files work. You can simply use different directories within the same repository to separate code and data, still benefit from having them in a single repo, and not endanger their respective citability when you put a CFF file into each directory. There is also an argument whether GitHub repositories are a suitable place for research data, but it's a point I'm deliberately not making here.
2. There is tooling available (and upcoming, e.g., [here](https://github.com/SciCodes/Planning/issues/10)) for CFF files that may help you keep your citation metadata updated semi-automatically at least, so that the manual burden is lessened as far as possible.

I'm closing this issue as we will not implement `type` arrays at this time, but feel free to keep using it for further discussion.
Thanks!
