### ISSUE TITLE
[Question] How to Correctly Cite CFF Repositories?

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#375]
Dear maintainers,

First of all, thank you for your work.  I am new to this standard and would like to apply it to my own repositories.  After working through your guideline for the latest version, 1.2.0, I am unsure how to correctly cite your repositories in order to honour your authorship of this standard appropriately.

The questions can be summarised as follows, explanations for them are provided below.

1. [x] How to basically cite another repository using the CFF standard?
2. [x] Which repositories should be cited?
3. [x] Can citation files be hard coded in templates or redistributed in any way?

# How to Basically Cite Another Repository Using the CFF Standard?

According to the guideline you provide in this repository, I understand that the meta data of the `CITATION.cff` from the repository to be cited (*source repository*) should be added to the `references` section in one's own repository (*target repository*).  The question is about the amount of meta data which should be included.

One possibility, the **maximal approach**, might be to just coping all lines -- except the `cff-version`, `message` and `references` section -- from the source repository and pasting them in the `CITATION.cff` of the target repository.  That way, literally *any* information of the source repository will be listed in the `references` section of the target repository.

But since GitHub automatically parses such `CITATION.cff` configuration files using your `ruby-cff` library and presents the parsing results in a "Cite this repository" text box on the concerning project's welcome page, I am unsure whether *these* meta data would suffice, as well, after being converted from the resulting BibTeX entry back to a CFF.  These meta data are based on the `preferred-citation`, so basically they refer to the source repository, as well.  I would like to name this approach **minimal**.

Furthermore, there is also a somehow **extended** approach of citing other repositories.  For instance, I like preparing repository manuals for my repositories.  These manuals are compiled from the contained README, CHANGELOG and LICENSE files and, hence, contain the most important information about the concerning project.  Since I use Pandoc therefore, the manual is compiled using LaTeX internally such that I could attach a bibliography, as well, or at least copy and paste the APA citation string to the repository's README.  Using this approach in addition to one of the others from above, the source repository would be definitely cited in the target repository.

My question is:  which combination of these three approaches is the recommended one in order to cite another repository?  I myself would prefer the extended maximal approach -- adding all meta data from the source repository in the target repository's `references` section *and* citing GitHub's parsing results with both the APA and BibTeX entries in the corresponding repository manual.

Furthermore, how to cite a repository which does not even contain a `CITATION.cff` or whose `CITATION` file does not meet the CFF 1.2.0 standard?  What is the best practice therefore?

# Which Repositories Should be Cited?

Since I worked through the guideline of *this* repository, I would like to definitely cite it in *every* of my `CITATION.cff`s -- just for completeness.  In addition, I used your `cffconvert` in order to verify the syntactic correctness of the resulting citation file, so I would guess that I rather should cite its repository, as well.

But what about the `ruby-cff` library which is applied by GitHub automatically?  I am sure that it would not be fault to cite it anyway; but if a software is applied on one of my repositories without being invoked actively by me:  do I need to cite it?  Or can I just assume it a standard which does not need to be cited?

In general:  I assume that any submodule (which has an appropriate `CITATION.cff`) should be cited as well as any software and / or paper which had a major impact on the development.  But when should I stop citing software?  Do I need to cite even the IDE I used for development?  Or even the operating system?  What about software I did not invoke myself, such as the `ruby-cff` example from above?

# Can Citation Files be Hard Coded in Templates or Redistributed in any Way?

Since I typically use the GPL 2.0 license for my repositories, I created a repository for source file templates.  These always contain the default GPL 2.0 license text as well as a sane minimal functionality such that I can rely on those templates in order to have working source files which only need to "fill" with the intended functionality.

I started to create a template for my personal `CITATION.cff`, as well, but it turned out to do not meet the CFF standard.  I oriented on the corresponding section in the GitHub manual which, well, just contains an absolutely minimum of information about the CFF standard, not including the ability to name references.  I would like to fix it but I need to know whether I am allowed to hard code your repositories' citation meta data in a GPL 2.0 template in the `references` section.  The question here is merely:  if a certain citation file does not contain the license text of the license which the concerning repository belongs to, is it still bound to the repository's license?

Since I would fix the template *after* working through your guideline in this repository, I would like to cite it appropriately in the template.  Due to *this* repository being licensed CC-BY-4.0, this should be no problem in the sense of license compatibility.  But the issue becomes difficult when thinking about `cffconvert` which I would like to use in order to verify the correctness of the resulting template since it has an Apache 2.0 license which I first would need to check for compatibility with my preferred license, GPL 2.0, which the template belongs to.

The interesting point is the license text:  your citation files do not contain the minimal license text of their respective licenses but my template does.  Hence, the template is clearly licensed GPL 2.0 but one could wonder whether your citation files are also distributed under their respective repositories' licenses.

# Conclusion

I know these might be a bit complicated, strange and, to some point, also pathological questions.  I would appreciate your help to find answers for them and to discuss the possible options with you in order to also help the people with the same questions to find solutions to similar questions.  Furthermore, the results of the discussion might be used to enhance the current version of the guideline for future versions of the CFF standard.

**Comment by sdruskat** [comment]
Thanks, @kevinmatthes, for this issue. As it is quite elaborate, please give us a day or two for a reply 🙂.

**Comment by kevinmatthes** [comment]
No problem, take your time.  Meanwhile, I am going to prepare a sample executable in order to illustrate the citing approaches in the first question.

**Comment by kevinmatthes** [comment]
Okay, I finished the basic work on a simple prototype which applies the basic ideas of the named approaches.  You can find it here:  https://github.com/kevinmatthes/cffreference.  It is written in Haskell and licensed GPL 2.0.

It reads a given `CITATION.cff` and extracts the required citation information to a certain output file.  It basically applies maximum approach from the first question with the difference that -- in case it should be configured -- a `preferred-citation` will be used, by default.

Furthermore, this repository can now be used as a practical example in order to answer the questions of this issue.

Regarding the first question:  at the moment, I cite three of your repositories (this one (`type: standard`), `cff-converter-python` (`type: software`) and `ruby-cff` (`type: software-code`)) as well as the main repository of GNU Octave (`type: manual` -- due to their preferred citation; see https://github.com/gnu-octave/octave/blob/default/CITATION for details).  Since I authored the submodules myself, I am going to cite them, as well, as soon as I added dedicated `CITATION.cff`s to them.  Is it enough to reference the repositories the way I did or shall I also cite them in the repository manual of `cffreference`?

Regarding the second question:  I obviously need to cite this repository since I oriented on the schema guideline you provide in order to define the tool's behaviour.  Furthermore, I validated the output of the tool using `cffconvert`, so I cited it as well.  GNU Octave takes care for the build routine, so it was cited, too.  Your `ruby-cff` was different from the other `CITATION.cff`s, so I added it, as well, since it helped me to find some bugs in the current code.  It was basically cited because GitHub will apply on my `CITATION.cff`, not because I would have applied it myself.  But due to the bug its `CITATION.cff` helped me to fix, I would tend to leave it in.  For other projects:  do I need to cite your `ruby-cff` library just because GitHub will apply it on my citation configuration file?

Regarding the third question:  as I wrote in this issue's description, I would like to create something like a template I can reuse in future repositories to create an appropriate `CITATION.cff` for them.  Am I allowed to hard code at least your repositories in the template's `references` section?

**Comment by kevinmatthes** [comment]
Just for completeness:  the named tool, [cffreference](https://github.com/kevinmatthes/cffreference), is also the topic of #376.

**Comment by kevinmatthes** [comment]
After taking some time to consider the possibilities of the CFF standard, the three questions were reduced to the following:

1. If a given `CITATION.cff` neither contains a `preferred-citation` nor any `type` line:  what is the best practice to set its type for `references`?  (Please see also the table below.)
2. (became obsolete)
3. Which license do the parsing results of `ruby-cff` have?

At the moment, I cite your repositories as follows (please correct me if I am wrong):

| Repository | Type | Explanation |
|-|-|-|
| `citation-file-format` | `standard` | I consider CFF a community standard. |
| `cff-converter-python` | `software` | The provided source code can be executed as a standalone application. |
| `ruby-cff` | `software-code` | The repository provides rather a library than an application. |

**Comment by jspaaks** [comment]
Thank you @kevinmatthes for making the issue. It is quite a lot to unpack but let's start with some of the (hopefully) simpler things and see how far we get.

To help the discussion, the basic structure of a `CITATION.cff` file is as follows:

1. keys like `title`, `authors`, `message`, `repository-code`, etc that describe "this" work, be that software or a dataset
2. `preferred-citation`, an optional key that has its own properties. `preferred-citation` can be used if you want to redirect credit away from the "this" work and have people cite whatever is described under `preferred-citation` instead.
3. `references`, an optional key that is an array of items, each of which representing a giant whose shoulders your work stands on. For example, if the "this" work is a software, `references` may include the metadata for any of the following:
    1. a paper that helped you create the software
    2. a previous implementation attempt that somebody made which inspired you to write your software (even if you only used ideas or patterns and didn't copy anything)
    3. a git submodule that is bundled with your software
    4. the upstream that you forked off of
    5. etc.

I've extracted some topics from your post:

- citing another repo
- citing ruby-cff
- citing a repository with problematic metadata
- which repositories should be cited
- Citing cffconvert

I'll try to elaborate on them in the sections below

**citing another repo**

The `CITATION.cff` file that accomplishes this contains whatever metadata is appropriate for describing the "this" work, as well as whatever metadata describes the "another" repository as an item in the `references` array. For example something like:

```yaml
authors:
  -
    family-names: Lastname
    given-names: Firstname
cff-version: "1.2.0"
message: "Please cite this software using these metadata"
references:
  -
    authors:
      -
        family-names: "Other work author's lastname"
        given-names: "Other work author's firstname"
        repository-code: "https://github.com/someorg/the-other-repository"
        title: "The title for the other work"
        type: software
title: "Title of the 'this' work"
version: "4.5.6"
```

If "Another repository" includes a `CITATION.cff`, you may use whatever metadata you find there, but note that you are not required to use exactly what is on offer there. For example, you can make the `references` item in your `CITATION.cff` file more precise by including a git tag or a SHA when the other work's CITATION.cff file only lists the plain URL. Or you may make it more robust against changes by including a persistent identifier such as a DOI for the work.

BTW you are not allowed to include `references` for any item in `references`. Doing so invalidates the `CITATION.cff` file.

**citing ruby-cff**

Since "this" work does not depend on ruby-cff for its results, its functioning, its ideas, etc, I don't think you are obliged to include it in "this" work's `CITATION.cff` file.

**citing a repository with problematic metadata**

If you want to cite a repository that

1. has no metadata,
2. has an invalid `CITATION.cff` file,
3. has a `CITATION` file which is not machine readable,

give it your best effort to identify at least the minimal information: For example for `authors` you can use aliases such as github user names, or you can use entities instead of persons. Something like:

```yaml
# (keys describing "this" work omitted)
references:
  -
    authors:
      -
        name: The Numpy Team   # entity instead of person
      -
        alias: jspaaks         # use 'alias' if you don't know or don't want
                               # to include the person's name
```

Besides `authors`, the CFF 1.2.0 standard requires you to include a `title` and a `type` as well. If the authors don't state the title of the work, you may pick one yourself, for example using the H1 heading or other prose from their README. If that can't be used for whatever reason, you can use the organization name and repo name and concatenate those, or you may look at whether there are releases that have names and use those instead. With regard to `type`, just pick one from the list of authorized names (see https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#definitionsreferencetype for the list).

**which repositories should be cited**

_" I need to know whether I am allowed to hard code your repositories' citation meta data in a GPL 2.0 template in the references section."_ Yes you are allowed to do this. This small part of our work is not a Creative Work in itself and is therefore not covered by copyright. Sidenote: I don't think you need to include a reference to the Citation File Format specification if your "this" work is something unrelated to citation (which I assumed it is).

_" The question here is merely: if a certain citation file does not contain the license text of the license which the concerning repository belongs to, is it still bound to the repository's license?"_

My understanding is that the repository's license covers the complete contents of the repo, regardless of whether each individual file contains a copy of the license text (or a short version thereof).

**Citing cffconvert**

Best practice is to only include a reference to `cffconvert` if your work uses `cffconvert` in some important/meaningful way. For example if your work is a converter service that uses `cffconvert` as a library, that would establish importance. If you're just running `cffconvert` to validate `CITATION.cff` (a file that isn't a meaningful part of the "this" work), I think you don't need to include `cffconvert` as an item in the "this" work's `references`.

**Comment by sdruskat** [comment]
I'm also going to add some - perhaps more high-level - comments, as I think that some of the questions root in the understanding of software citation.

### Re: How to Basically Cite Another Repository Using the CFF Standard?

CFF mainly targets software citation for academic use cases, i.e., providing information related to the provenance of research results reported in academic work (papers, etc.). This kind of citation needs what you call the "minimum" amount of citation information, which in turn extends the set of metadata you would need for a written work (a paper) by, e.g., version and accessibility information (e.g., `repository-code`).

This is all based on the principles of software citation that are outlined in [this paper](https://peerj.com/articles/cs-86/).

So for academic purposes, the minimal set of metadata that you would want to include in `references` is: `authors`, `title`, `version`, `date-released` or `date-published` (if the software was published), `doi` (or other identifier), the place of publication (`repository-code` or `repository-artifact` or `repository` (e.g., if the software is published in an open access repo that provides DOIs).

### Can Citation Files be Hard Coded in Templates or Redistributed in any Way?

Short answer: Yes, they can.

Longer answer: I Am Not A Lawyer, but IMHO as metadata files, `CITATION.cff` files usually don't reach the threshold of originality that would qualify them for copyright and licensing. Hence, I don't see any issue with hard-coding, templating and re-distributing them.

---

### Answers to sub-questions, and comments

> Is it enough to reference the repositories the way I did or shall I also cite them in the repository manual of `cffreference`?

That depends on your definition of "enough" 😉. If you expect that people are careful enough to read the `CITATION.cff` file and process the information in good faith and according to good scientific practice: yes. If you expect the metadata to be used downstream by machine clients (e.g., indexers, harvesters, etc.): yes. If you want to avoid duplicating (and having to maintain duplicate) information: yes. If you think that people will miss this information: better put them in the manual as well. Personally, I wouldn't duplicate the information, as it's the sole purpose of CFF to avoid having to do this (and others having to read such strings).

> For other projects: do I need to cite your `ruby-cff` library just because GitHub will apply it on my citation configuration file?

Short answer: no, you don't. Related: [my comment above](), [@jspaaks's comment](https://github.com/citation-file-format/citation-file-format/issues/375#issuecomment-1153681604#citing-ruby-cff).

> Am I allowed to hard code at least your repositories in the template's `references` section?

Absolutely, please do so!

> At the moment, I cite your repositories as follows (please correct me if I am wrong):
> Repository 	Type 	Explanation
> `citation-file-format` 	`standard` 	I consider CFF a community standard.
> `cff-converter-python` 	`software` 	The provided source code can be executed as a standalone application.
> `ruby-cff` 	`software-code` 	The repository provides rather a library than an application.

I think this sums it up nicely, I don't see any issues with citing like this 👍.

**Comment by sdruskat** [comment]
On another note, I really like `cffreference` and would submit that it could come in really handy when compiling more elaborate metadata from CFF files and repositories, e.g., when compiling a generic description of software in a CodeMeta file or similar.

Should we add it to the [list of CFF-related tools](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#tools-to-work-with-citationcff-files-wrench)?

**Comment by kevinmatthes** [comment]
Thank you, @sdruskat and @jspaaks, for your helpful feedback and answers!  This answers my questions and helps me a lot to correctly apply the CFF standard.
