### ISSUE TITLE
Feature request: supporting .yaml/.yml extensions

### ISSUE THREAD

**Issue by jamesbraza** [citation-file-format/citation-file-format#377]
First of all, `CITATION.cff` is really cool and am quite happy this exists!

I am a software engineer who uses [`yamllint`](https://github.com/adrienverge/yamllint) to automatically lint YAML files.  Its [default configuration](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration) looks for `*.yml` or `*.yaml` files.

Is it possible to rename `CITATION.cff` to `CITATION.yaml`, while maintaining GitHub's "cite this repository" support?  And if it's not possible, could this be a feature entertained?

**Comment by kevinmatthes** [comment]
I would like to suggest some simple workarounds in order to enable requested functionality with minimal changes:

* Add the `*.cff` extension to the respective configuration files for `yamllint` (block `yaml-files`) and in the workflow's linting job (request `*.cff` in addition to `*.yaml` and `*.yml`).
* Implement a small wrapper which renames the file for linting and renames it afterwards.

Would one of these suggestions work for you?

**Comment by jamesbraza** [comment]
I am invoking `yamllint` via `pre-commit`, so I added a regex `\.(ya?ml(lint)?|cff)$` to the `files` option.  I already have a workaround/solution.

This issue was more that I just thought it might be nice to leverage a standard extension for `CITATION.cff`.  The main benefits of using a `.yaml` extension are YAML syntax highlighting in IDEs and easy integration with YAML formatting/linting tools.  Feel free to close this ticket.

**Comment by kevinmatthes** [comment]
I am sorry, I misunderstood the purpose of this issue.  I assumed that you were looking for the requested functionality due to general problems with CFF and the named tool.

GitHub parses CFF files using the `ruby-cff` library of this namespace.  Hence, the additional extensions should be added especially there but also in the `cffconvert` repositories (the Python 3 CLI and its Docker image for the corresponding GitHub Action).  It might help to suggest the necessary fixes in detail in issues or provide respective patches in pull requests in the corresponding repositories.  That way, I consider it very likely to realise the suggested feature soon.  (In order to avoid further misunderstandings:  I am just a CFF user myself and not a maintainer; I just proposed the suggestions in order to help in urgent cases to reduce the waiting time.)

By the way:  VS Code-like IDEs, such as VS Code or VSCodium, already associate CFF with YAML.  And many other editors should provide a corresponding configuration file to add CFF as a YAML dialect by hand, as well.  Maybe this could be a further option, as well.

**Comment by sdruskat** [comment]
> First of all, `CITATION.cff` is really cool and am quite happy this exists!

Thanks, @jamesbraza! :pray:
 
> I am a software engineer who uses [`yamllint`](https://github.com/adrienverge/yamllint) to automatically lint YAML files. Its [default configuration](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration) looks for `*.yml` or `*.yaml` files.
> 
> Is it possible to rename `CITATION.cff` to `CITATION.yaml`, while maintaining GitHub's "cite this repository" support? And if it's not possible, could this be a feature entertained?

As per the [ruby-cff](https://github.com/citation-file-format/ruby-cff) library that does the conversion work within GitHub, this isn't possible (see https://github.com/citation-file-format/ruby-cff/blob/main/lib/cff/file.rb#L41), and would also violate the [specifications](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#general-structure-of-a-citationcff-file).

From a usability perspective, the `.cff` extension IMHO helps associating the respective files with the CFF format as such, whereas `CITATION.yaml` files would muddy the waters (at least for human users, but potentially also for computational approaches).

I think that the advantages of having a semantically reliable file name in combination with the existing JSON schema and its supported uses in, e.g., IDEs outweighs the disadvantages of having to lightly wrap or configure for linting applications.

Also, thank you @kevinmatthes, for your helpful comments and suggestions! These are very welcome, especially since the current workload of the maintainers doesn't always allow for timely replies (as you are experienceing yourself as well).

I'll close this issue, but feel free to re-open should there be need for further discussion.
