### ISSUE TITLE
[Question] Tree-Sitter(s) for CFF?

### ISSUE THREAD

**Issue by kevinmatthes** [citation-file-format/citation-file-format#389]
[Tree-Sitter](https://github.com/tree-sitter/tree-sitter)s are syntax parsers with which some editors, like [Zee](https://github.com/zee-editor/zee) or [Helix](https://github.com/helix-editor/helix), manage their syntax highlighting for the respective coding languages.  Although CFF could be highlighted with a simple YAML Tree-Sitter, a dedicated CFF could focus on the permitted fields and their dependencies.  A specialised Tree-Sitter would help to integrate the CFF standard in many editors and, thus, to interact with CFF appropriately.

I would like to add a CFF syntax highlighting support for Zee.  I already took a look at the Tool Catalogue table in this repository's README but I did not found a Tree-Sitter, which are usually written in C with bindings for Rust and some other common coding languages.  Maybe I just oversaw them but still:  are there any Tree-Sitters for CFF?

**Comment by sdruskat** [comment]
Hi @kevinmatthes, and sorry for the late reply, this issue came in during holiday season.

Thanks for creating the issue, I am not aware of any tree-sitters for CFF. I guess this makes it a "build-it-yourself" situation. Of course we'll be very happy to add any CFF tree-sitters to the tools overview.

**Comment by sdruskat** [comment]
Please re-open if there is need for further discussion/questions, etc.
