### ISSUE TITLE
Larger 'type of the work'-enum

### ISSUE THREAD

**Issue by kaat0** [citation-file-format/citation-file-format#430]
Hi,

I am working on an Open Educational Ressource (OER) as a LaTeX document. I want to use the CITATION.cff file, but it only allows for two types in the `schema.json`: `dataset` and `software` (line 1856).
Is there a reason for that?

Even Zenodo allows for more types:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/142348/222511574-980ad61e-7860-4607-bab9-2c5fd410744c.png">

An easy fix is to copy the enum types from `reference` from line 1578, even though OER does not fit in there.
Is there anything that might argue against this?

Thanks for the great work,
Martin

**Comment by atruskie** [comment]
I'll second this. I have several repos that are:

- documentation only (markdown)
- websites
- lessons / teaching materials

Seems like the type enum is too narrow.

**Comment by sdruskat** [comment]
Thanks, @kaat0 and @atruskie, for this discussion.

The Citation File Format has a very narrow scope: _citation_ metadata for _software_. (`dataset` is there due to a compromise, and will remain experimental and essentially unsupported for the time being.) This is because while there are formats for providing metadata with different scopes (e.g., general descriptive metadata far beyond citation purposes) or for a range of "types of the work" (e.g., BibTeX), none of these work well both technically and semantically for software.

It is tempting to use the format for other types and make it more universally applicable, but a) we don't have enough resources to do this, and b) we would probably end up with a situation similar to [this XKCD comic](https://xkcd.com/927/).

Hence, we will not at this point be able to support other types beyond `software`. I'm sorry that this will not help you in your situation. 

Depending on your use case (do you "just" want the GitHub widget, for example?), you can of course consider using either `software` or `dataset`, this information is not (AFAIK) encoded in the snippets you get in the widget. Or there may be other metadata formats better suited to describing your resources.

**Comment by atruskie** [comment]
While I do fully appreciate that XKCD comic, I might suggest that the gap that needs to be filled is (to modify your words):

> The Citation File Format lets you provide citation metadata for in plaintext files that are easy to read by both humans and machines.

This gap needed to be filled so citation information could be stored in a manner suitable for storing in version control.

Zenodo is the other half of that gap - creating DOIs for resources not covered by academic publishing.

Case in point: this very repo has a citation.cff file. It is arguable that is by definition not software and in fact, by volume, mostly documentation and a specification.

I'm a research engineer too. I write papers (rarely), I write software, and I publish datasets. But more and more the single thing I do most, is write documentation, in GitHub repositories. As tooling support grows around citation.cff (GitHub integration and Zenodo integration) it becomes a pain point to be restrictive about what can be described by citation.cff when so many much of our RSE workflows involve these tools (Git, GitHub, Zenodo).

**Comment by kaat0** [comment]
Thanks @sdruskat for your answer!

I do understand the need to narrow the scope in order to have enough resources for development. @sdruskat could you please elaborate on how much more resources it would need to broaden the scope? E.g. how many resources are needed for the dataset part?

AFAIK there are no standards/schemas for citing OER on Github, currently. So the XKCD comic is actually an argument to broaden the scope of this standard to avoid having more than one in the scenario @atruskie describes.

My workaround, for now, would be to just ignore the current enum type and put in something I like.

**Comment by sdruskat** [comment]
Thanks @kaat0 and @atruskie. I see your points. Let me mull over this a bit and get back to you.

One point to be made re documentation (for software and datasets) is that it can be seen as part of the object it documents. Also, documentation is regularly versioned in the same repo as the software, and in these cases arguably falls under the `software` type.

Also, this is generally a decision of setting cut-off points, i.e., it depends on the resolution of the argument if something is _software_ (including, e.g., build instructions, documentation, metadata files), or if everything is a _complex object_ (e.g., are constants really software or data, etc.). For your use cases, I lean towards arguing that documentation is part of the object, whereas OERs usually aren't mainly software, even if they are implemented using software. For this argumentation, CFF is a valid format for documentation, but not for OERs.

**Comment by kevinmatthes** [comment]
From my point of view, there already *should* be a workaround implemented into the CFF v1.2.0 standard solving the issue regarding the work type enum:  citation redirection by `preferred-citation`.  Again, this depends on the exact use case but in most cases, this feature enables users to access more work types.

When I need to define a citation entry for referencing in other projects and / or CFFs, I usually begin with the `preferred-citation` and add some minimal / mock data around it for ensuring the CFF to be still valid.  Then, I can grab the data with my [`cffreference`](https://github.com/kevinmatthes/aeruginous-rs) which I have designed to respect the `preferred-citation` clause, if available, in the input CFF rather than the top level data.

If you are more interested in the GiHub citation blob's output, there also should be some equivalent logic in the [rendering library](https://github.com/citation-file-format/ruby-cff/blob/main/lib/cff/formatters/bibtex.rb) in order to give the `preferred-citation` a higher precedence than the top level data such that the citation redirection should work there, as well.  However, I need to admit that I am not used to the Ruby coding language so I also might have misunderstood the source code.  But still, the project belongs to the official CFF namespace such that, in case that certain feature should not already be implemented, it could be simply requested for addition in a future release.

**Comment by MattF-NSIDC** [comment]
Apologies or the duplicate issue :point_up: , I searched poorly I think. I was hoping to find a way to avoid manually editing my Zenodo records to change their type post-release, but I see there's a larger discussion here.

>>I'm a research engineer too. I write papers (rarely), I write software, and I publish datasets. But more and more the single thing I do most, is write documentation, in GitHub repositories. As tooling support grows around citation.cff (GitHub integration and Zenodo integration) it becomes a pain point to be restrictive about what can be described by citation.cff when so much of our RSE workflows involve these tools (Git, GitHub, Zenodo).
>
>One point to be made re documentation (for software and datasets) is that it can be seen as part of the object it documents

I resonated with @atruskie's comment. I'm writing documentation, presentations, tutorials, workshops, all as Git repositories (often using Quarto), and I often find it hard to see them as *part of* a related software/dataset. For example, [this workshop curriculum](https://github.com/qgreenland-workshop-2023-researcher/qgreenland-workshop-2023-researcher.github.io) my team developed _is_ related to the QGreenland software project, but its subject matter is much broader. I'm also giving a lightning talk about lessons learned from this workshop at a conference, and [I'm managing that in a GitHub repository too](https://github.com/nsidc/agu2023-qgreenland-cryocloud). These are all related, but distinct citations. Sometimes, I'm writing documentation about processes, hardware, software deployment configurations, best practices, or methodologies. 

Anyway, I really appreciate your openness to continue hearing input on this issue!

**Comment by MakisH** [comment]
Documenting another example:

In the [teaching RSE project](https://github.com/CaptainSifff/paper_teaching-learning-RSE) we are collaboratively writing papers that we eventually want to publish in peer-reviewed journals. However, people sometimes want to refer to this repository to cite work in progress. Therefore, we are discussing adding a CFF file: https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/253

For this use case, similarly to the papers and documentation mentioned by others above, neither the type `software` nor `data` fits.
