### ISSUE TITLE
.cff is a YAML file but YAML is never mentioned

### ISSUE THREAD

**Issue by julianstirling** [citation-file-format/citation-file-format#449]
The CFF file appears to use YAML syntax, I can only verify that this is how it is parsed find this by delving into code. The README should specifically say this.

It seems somehow wrong for a project whose core purpose is to encourage citation is using another format without any reference back to the standard they are using.

**Comment by kevinmatthes** [comment]
@julianstirling

The main documentation of this project is located in `schema-guide.md` which also contains information on YAML 1.2 being applied as base format:  https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md?plain=1#L9.  The README provides a link to the schema guide in the second paragraph:  https://github.com/citation-file-format/citation-file-format/blob/main/README.md?plain=1#L46.  Furthermore, the fact that YAML is used can be also found explicitly in the README's first paragraph:  https://github.com/citation-file-format/citation-file-format/blob/main/README.md?plain=1#L16.

Does this answer your question?

**Comment by kevinmatthes** [comment]
> the many files I searched through

Is it not more obvious to have a look at the source code view of one file before beginning to search through other *files*?  And which *files* do you mean?

**Comment by julianstirling** [comment]
Obviously it wasn't obvious to me or I would have done. I am simply reporting back that I spent some time confused as it wasn't clear to me. You are welcome to close the issue on the grounds that you think I am an idiot, but trying to convince me that actually I wasn't actually confused is somewhat silly.

Clearly I am not welcome here, I'll close the issue and go away. Enjoy your life

**Comment by jspaaks** [comment]
Hi @julianstirling,
First off, I'm sorry we made you feel unwelcome, that wasn't our intent. Second, thank you for reporting your experience. Such reports are valuable to us and to the future of this project. Then about YAML: I agree it is expected to find some reference to the fact that CITATION.cff files are YAML 1.2, and indeed such reference was included (albeit a bit hidden, in schema-guide.md). This is because we opted not to have much technical detail in the main README, as we felt it would make that document long and that would negatively affect the readability. While this is a bit of a tradeoff in that not all information is included in the main README, I still think it is the right way to go.

Hope this clears things up!

Best regards,
Jurriaan
