### ISSUE TITLE
Create more accessible landing page for CFF

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#76]
There should be a more accessbile landing page for CFF, outlining just a few things, and presenting examples, a roadmap, and links to tooling and coverage.

**Comment by jspaaks** [comment]
My suggestion would be smthing along the lines of the below (not set in stone of course, just first thoughts). Whatever we decide, IMHO the key to this page's success is that it is short (and therefore incomplete)

# what is a CITATION.cff file? 
(keep this section very short)
(We should reserve the "what is the CFF format/spec/schema" for (much) later)
Maybe somthing like: A plain text file with machine readable citation information, which code developers can include in their repositories in order to promote accurate citation
(if we decide we need a minimal example, this would be the place)

# why do you need it
(keep this section very short)
see Citability section here https://blog.esciencecenter.nl/the-research-software-directory-and-how-it-promotes-software-citation-4bd2137a6b8. Maybe something like:
"Citing research software is intrinsically more difficult than citing, say, research papers, because relevant information is often a lot less obvious. For example, a person wanting to cite software may face questions like:
What is the name of the software (given that it’s probably not my_scripts/run.m or analysis.py)?
What label should I use to uniquely identify the version of the software?
What is the appropriate set of people that should be identified as authors?
The burden of answering these questions typically lies with the person who wants to cite, even though we, as the developers of the software, are in a much better position to answer those questions accurately and consistently."

# call to action
At this point I'd like to see a call to action, something like "Get started with adding citation data to your software" with pointers to cffinit or a (to be developed...) interactive cli or something

# tooling
a description of available tooling; maybe just described at the functional level, like "an intializer", "a validator", "a converter", etc.

# events
an overview of past and upcoming events

I don;t think this is a good place for the roadmap; we could just keep that in a github repo somewhere. I'm on the fence regarding contributing instructions/kind of leaning towards having a short invitation to look at how to contribute.

Interested to know what you think.

**Comment by sdruskat** [comment]
Closing as the suggested changes are live.
