### ISSUE TITLE
how to store an author who is only known by an alias, e.g. a github login

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/citation-file-format#93]
The current CFF spec 1.0.3 says the ``family-names`` and ``given-names`` keys are required for authors, but what if an author is only known by an alias, for example the GitHub login.

**Comment by sdruskat** [comment]
Let's introduce `alias` like this (https://github.com/citation-file-format/citation-file-format/issues/93#issuecomment-550995529), after we switch to yatiml.

**Comment by LourensVeen** [comment]
Note that not everybody may have both family names and given names (e.g. when citing "How to saw your research assistant in half and then put her back together" by P. Jilette and Teller), but you can put an arbitrary check-and-raise in the __init__ with YAtiML, so we can check that at least one of the three is there.

I like having aliases also from an inclusivity perspective. While it would probably be good to have at least one non-anonymous contributor that you can talk to at conferences and such, people may want to contribute to software who prefer not to give their real or legal name for reasons of privacy (avoiding harassment) or because their legal name does not match their gender identity. Their contribution should still be acknowledged, even if pseudonymously. Of course in an ideal world that would not be necessary, but well, sometimes this world isn't ideal.
